[package]
name = "geng_tas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geng = { git = "https://github.com/nertsal/geng", branch = "tas" }
serde = { version = "1.0.151", features = ["derive"] }
